name: Cordova Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Cordova and build
      run: |
        npm install -g cordova
        cordova platform add android
        cordova build android --release

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: palabras-app-apk
        path: platforms/android/app/build/outputs/apk/**debug**/app-debug.apk
